version: '3'

services:
  streamlit:
    build: 
        context: .
        dockerfile: streamlit\Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - api

  api:
    build:
        context: .
        dockerfile: api\Dockerfile
    
    ports:
      - 8001:8001

# version: '3'

# services:
#   api:
#     build: api/
      
#     ports: 
#       - 8001:8001
#     networks:
#       - deploy_network
#     container_name: api

#   streamlit:
#     build: streamlit/
#     depends_on:
#       - api
#     ports: 
#         - 8501:8501
#     networks:
#       - deploy_network
#     container_name: streamlit

# networks:
#   deploy_network:
#     driver: bridge
